### ISSUE TITLE
the pollyhook works but the example one i cant compile

### ISSUE THREAD

**Issue by Dj-jom2x** [stevemk14ebr/PolyHook_2_0#46]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1097	unknown attribute "no_init_all"	ExampleProject	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h	7597	
Error	LNK2001	unresolved external symbol "public: virtual class std::vector<class PLH::Instruction,class std::allocator<class PLH::Instruction> > __thiscall PLH::CapstoneDisassembler::disassemble(unsigned __int64,unsigned __int64,unsigned __int64)" (?disassemble@CapstoneDisassembler@PLH@@UAE?AV?$vector@VInstruction@PLH@@V?$allocator@VInstruction@PLH@@@std@@@std@@_K00@Z)	ExampleProject	C:\Users\mcskyblock\Desktop\nerd\PolyHook_2_0\ExampleProject\ExampleProject\build32\ExampleProject\ExampleProject.obj	1	
Error	LNK2019	unresolved external symbol "public: virtual bool __thiscall PLH::Detour::unHook(void)" (?unHook@Detour@PLH@@UAE_NXZ) referenced in function _main	ExampleProject	C:\Users\mcskyblock\Desktop\nerd\PolyHook_2_0\ExampleProject\ExampleProject\build32\ExampleProject\ExampleProject.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall PLH::x86Detour::x86Detour(char const *,char const *,unsigned __int64 *,class PLH::ADisassembler &)" (??0x86Detour@PLH@@QAE@PBD0PA_KAAVADisassembler@1@@Z) referenced in function _main	ExampleProject	C:\Users\mcskyblock\Desktop\nerd\PolyHook_2_0\ExampleProject\ExampleProject\build32\ExampleProject\ExampleProject.obj	1	
Error	LNK2019	unresolved external symbol "public: virtual bool __thiscall PLH::x86Detour::hook(void)" (?hook@x86Detour@PLH@@UAE_NXZ) referenced in function _main	ExampleProject	C:\Users\mcskyblock\Desktop\nerd\PolyHook_2_0\ExampleProject\ExampleProject\build32\ExampleProject\ExampleProject.obj	1	
Error	LNK1120	4 unresolved externals	ExampleProject	C:\Users\mcskyblock\Desktop\nerd\PolyHook_2_0\ExampleProject\ExampleProject\build32\ExampleProject\Debug\ExampleProject.exe	1	

```

the pollyhook works but the example project one i cant compile..

i manage to make it work  on my pc.. but on my vps

**Comment by Dj-jom2x** [comment]
it seems building it using cmake fixis the PolyHook_2.lib became 2kb

**Comment by ExtReMLapin** [comment]
I actually have the same exact issue and I never used cmake before, how did you fix it exactly ?

**Comment by stevemk14ebr** [comment]
you should read the readme where I give exact steps on how to compile word for word

**Comment by Dj-jom2x** [comment]
At that time. it doesn't really work out of the box.. when I compile it to load it as cmake on vs2017 on my google RDP. it will throw. the same error as above.. and it still keeps looking for lib.. that always 2kb. **everything is successfully built but the example project is not.**

but on CMake, it works. its just work.. and the example project is working.

**Comment by stevemk14ebr** [comment]
the whole project is cmake, the example too. They are separate projects, so get compiled separately. It only works with cmake because I used a special flag to export all symbols like a Linux .so. This is also why the lib is so large. Again I documented all of this. The problem is not the lib, it is you guys not understanding cmake

**Comment by ExtReMLapin** [comment]
I never said the issue was caused by you, i just posted a solution for the next guys that will have this issue.

I'm just not familiar with CMake at all.
